debuggerd: Resolve tombstoned missing O_CREAT mode
 debuggerd/tombstoned/tombstoned.cpp:115:92:
  error: 'openat' has superfluous mode bits; missing O_CREAT?
    unique_fd result(openat(dir_fd_, ".",
    O_WRONLY | O_APPEND | O_TMPFILE | O_CLOEXEC, 0640));

Change-Id: Iae787e477b7eab1f11c79f30c35fd6808959e38a

Former-commit-id: 347b40cb55bba9927da48200ec53c9d9457d90c8
Former-commit-id: a6d88e276dc789c70371c745246990826e1354f0
Former-commit-id: 06508be1981b15eeffb4a17be6d6e785e6e98dca